// Generated by CoffeeScript 1.3.3

Ext.define("Realtor.view.Listing", {
    extend: "Ext.container.Container",
    alias: "widget.realtor-view-listing",
    controller: "Realtor.controller.ListingController",
    inject: ["listingStore"],
    layout: "anchor",
    config: {
        listingStore: null,
    },
    initComponent: function() {
        Ext.applyIf(this, {
            items: [{
                xtype: "gridpanel",
                itemId: "listingGridPanel",
                store: this.getListingStore(),
                columnLines: true,
                anchor: "100% 100%",
                columns: [{
                    xtype: "gridcolumn",
                    dataIndex: "title",
                    text: "Title",
                    flex: 1
                }, {
                    xtype: "numbercolumn",
                    dataIndex: "price",
                    text: "Price",
                    format: "0.00"
                }, {
                    xtype: "gridcolumn",
                    dataIndex: "currency",
                    text: "Currency",
                }, {
                    xtype: "gridcolumn",
                    dataIndex: "address",
                    text: "Address",
                }, {
                    xtype: "numbercolumn",
                    dataIndex: "area",
                    text: "Area",
                    format: "0.00"
                }, {
                    xtype: "gridcolumn",
                    dataIndex: "areaUnits",
                    text: "Units"
                }]
            }]
        });
        return this.callParent(arguments);
    }
});
