// Generated by CoffeeScript 1.3.3

Ext.define("Realtor.view.TestPanel1", {
  extend: "Ext.panel.Panel",
  alias: "widget.realtor-view-testpanel1",
  requires: ["Realtor.view.Listing"],
  controller: "Realtor.controller.TestPanel1Controller",
  inject: ["listingStore"],
  layout: "anchor",
  config: {
    companyStore: null,
  },
  title: "Panel Title",
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "realtor-view-listing"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
