// Generated by CoffeeScript 1.3.3

Ext.define("Realtor.store.ListingStore", {
  extend: "Ext.data.Store",
  requires: ["Realtor.model.Listing"],
  inject: ["appConfig"],
	 config: {
    appConfig: null
  },
  autoLoad: false,
  constructor: function(cfg) {
    cfg = cfg || {};
    return this.callParent([
      Ext.apply({
        model: "Realtor.model.Listing",
        proxy: {
          type: "ajax",
          url: "http://www.realtor.cf/api/listing",
          reader: {
            type: "json"
          }
        }
      }, cfg)
    ]);
  },
});
