// Generated by CoffeeScript 1.3.3

Ext.define("Realtor.model.Listing", {
  extend: "Ext.data.Model",
  fields: [{
      name: 'forSale',
      type: 'boolean'
    },

    {
      name: 'title'
    },

    {
      name: 'address'
    },

    {
      name: 'price',
      type: 'float'
    },

    {
      name: 'currency'
    },

    {
      name: 'area',
      type: 'float',
    },

    {
      name: 'areaUnits'
    },

    {
      name: 'numRooms',
      type: 'float',
    },

    {
      name: 'floor',
      type: 'integer',
    },

    {
      name: 'description'
    },

    {
      name: 'furnished',
      type: 'boolean',
    },

    {
      name: 'parking',
      type: 'integer',
    },

    {
      name: 'elevator',
      type: 'boolean',
    },

    {
      name: 'luxurious',
      type: 'boolean',
    },

    {
      name: 'alarm',
      type: 'boolean',
    },

    {
      name: 'ac',
      type: 'boolean',
    },

    {
      name: 'internet',
      type: 'boolean',
    },

    {
      name: 'visible',
      type: 'boolean',
    },
  ]
});
